### ISSUE TITLE
Kanji hover and anki

### ISSUE THREAD

**Issue by Yagxter** [cademcniven/Kanji-Hover#1]
I use your Eminent note type in Anki, and it often happens when I'm reviewing the cards. For some reason, the information for the kanji all appears on the back of the card at once. I have some screenshots, but I don't think I can send them here.
Anki version 2.1.66

**Comment by cademcniven** [comment]
Answered on discord. For anyone else with this issue, you have the old version of kanjihover -- remove it from your media folder and replace it with the latest release
